---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tsckoper/api/
    - /bin/cp server.js $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R node_modules $DEPLOYPATH
